# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd46791b20a2992603766abffcc7bfab61fd5602a44fd55341bebcb99c65a1b755143f021dd0d3c0816f9250182a45b48da488997e92cad7521eb99494e73b0a

test:
  secret_key_base: 859f0f73cb17e02c466e52248f429ba048ce72fc8dea224afa551e4c389300387505052ce1ac4d402d44805d34c8103b0f139a89a7c3a0972addbfd5065ab152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
